### ISSUE TITLE
Group Milestone - Implementation (Sprint 1)

### ISSUE THREAD

**Issue by hashamali** [quipit/quipit-android#10]
Main flow for circle creation, feed, notifications, navigation are nearly functionally complete. Next sprint will be wiring up models with Parse and putting the final touches on this functionality.
### Relevant issues
#2 #3 #4
### Gifs

![image](https://camo.githubusercontent.com/918984597f502e19454c35a284f2d3563a7bc9e0/687474703a2f2f692e67697068792e636f6d2f6c34316d337253465055726d384e78544f2e676966)

![image](https://cloud.githubusercontent.com/assets/5225346/10567560/f4e3ec4e-75bc-11e5-8961-72ae4eefff6c.png)

![image](https://cloud.githubusercontent.com/assets/5225346/10567562/fb23761a-75bc-11e5-9ac1-7a4d3e5c3d92.png)
## Reviewers
- [x] @codepath
- [x] @codepathreview

**Comment by hashamali** [comment]
A gif of the more full flow:

![](http://i.imgur.com/9Hz887q.gif)

**Comment by codepathreview** [comment]
:+1:  Nice work creating wire-frames and creating stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:
- Well created detailed stories/tasks.
- Consider diving a bigger parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
- Good job by everyone to (contribute)[https://github.com/quipit/quipit-android/graphs/contributors] to the project.  
- Consider creating a project wiki so you can have a thorough documentation of all design decisions made during the project.
- Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.
- Consider creating group [milestones/pull requests](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) to better track your progress and review each others code.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.
